apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-0003-stg
  namespace: argocd
  labels:
    app: test-0003
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Source configuration
  source:
    repoURL: git@github.com:shareit-solutions/test-0003
    targetRevision: develop  # Use develop branch for staging
    path: charts/app
    helm:
      valueFiles:
        - values.yaml
        - values-stg.yaml
      parameters:
        - name: app.name
          value: test-0003-stg
  
  # Destination configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: test-0003-stg
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  
  # Revision history
  revisionHistoryLimit: 3
  
  # Ignore differences
  ignoreDifferences:
    - group: apps
      kind: Deployment
      managedFieldsManagers:
        - kube-controller-manager